### ISSUE TITLE
Suggestion: Omit XML declaration / SVG namespace

### ISSUE THREAD

**Issue by heuer** [ideler/django-segno-qr#1]
Thanks for using Segno ;)

I added a hint to your project in the docs: https://segno.readthedocs.io/en/latest/web-development.html#django

This code in `segno_qr.py` creates a complete XML document with XML declaration and namespaces:

```python
    svg = BytesIO()
    qr.save(svg, 'svg', scale=size, dark=dark, light=light)
    result = svg.getvalue().decode('utf8')
    return mark_safe(result)
````

I suggest to omit the XML declaration and the SVG namespace since the latter is already known by HTML5 browsers.
Basically you can reduce the code to

```python
    result = qr.svg_inline(scale=size, dark=dark, light=light)
    return mark_safe(result)
```

The method `svg_inline` omits the XML declaration and the namespace declaration automatically and returns the SVG as string.
svg_inline was added in 1.2.0

If you don't want to rely on svg_inline, I suggest to change the code as follows:

```python
    svg = BytesIO()
    qr.save(svg, 'svg', xmldecl=False, svgns=False, nl=False, scale=size, dark=dark, light=light)
    result = svg.getvalue().decode('utf8')
    return mark_safe(result)
```

**Comment by nick-traeger** [comment]
Thanks for the suggestion. I have just implemented the change!
